### ISSUE TITLE
uninitialized constant MotionWiretap::Wiretap

### ISSUE THREAD

**Issue by emptyarray** [colinta/motion-wiretap#3]
I am doing `gem motion-wiretap` in my Gemfile and `require 'motion-wiretap'` in my Rakefile, but I get the following error:

```
uninitialized constant MotionWiretap::Wiretap (NameError)
 *** Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant MotionWiretap::Wiretap (NameError)
```

I'm not referencing MotionWiretap anywhere yet. `app.detect_dependencies` is `false`.

Thanks for looking into it... I'm looking forward to playing around with the gem.

**Comment by colinta** [comment]
Ah, I'll have to fix what order the files are added. I think I've only
tested it with detect_dependencies on.

**Comment by emptyarray** [comment]
Great, thanks.

**Comment by colinta** [comment]
Try out the latest - version 1.1.1 on rubygems.

**Comment by emptyarray** [comment]
Thanks... works fine now.

**Comment by colinta** [comment]
Is this resolved?  Please close the issue if there's nothing left to fix.
