### ISSUE TITLE
WiretapNotification

### ISSUE THREAD

**Issue by emptyarray** [colinta/motion-wiretap#4]
Attempting to wiretap a notification throws:

wiretap.rb:70:in `listen:': undefined method`<<' for nil:NilClass (NoMethodError)

This is because `WiretapNotification` doesn't call super, which means that `@listener_handlers` array is `nil`. I got around this by overriding `WiretapNotification`'s initialize and calling `super &block`(just `super` doesn't work). Not sure if this is the right way to go.

Thanks for the gem updates btw.

**Comment by colinta** [comment]
Ah thanks!  calling `super &block` is correct.  I've pushed version 1.1.5 which includes a fix, and I whipped up a quick spec for this, too!

**Comment by colinta** [comment]
Oh, and I _just now_ realized I hadn't been pushing to github, I had my commits going to a private repo!  oops... well everything is up-to-date now.
